name: SMPProtect
main: me.kevsal.minecraft.smpprotect.SMPProtect
version: ${project.version}
author: Kevinjss1/Kevinsal03
description: A Bukkit/Spigot/Paper plugin designed to protect private SMP servers from IP enumeration attacks.
api-version: 1.14

commands:
  trust-ip:
    usage: /<command> <ip>
    description: Add a new IP to the trusted database.
    aliases:
      - tip
  untrust-ip:
    usage: /<command> <ip>
    description: Remove an IP from the trusted database.
    aliases:
      - utip
  # TODO: Add list command

permissions:
  smpprotect.add:
    default: op
    description: Add IP
  smpprotect.remove:
    default: op
    description: Remove IP
  smpprotect.*:
    children:
      - smpprotect.add
      - smpprotect.remove
    default: op